### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by mansya** [Abhishek1103/echo-music-player#5]
Hi, @Abhishek1103 I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by Abhishek1103** [comment]
Hi, @mansya ,

I'm a fan of open source and it's an open project, you are more than welcome to contribute as u seem fit...!!

**Comment by mansya** [comment]
I have design a logo for this app. do you like it ? What do you think?
![echo music](https://user-images.githubusercontent.com/33461607/41194573-93bac99a-6c47-11e8-81f3-5afe17945cf5.png)

**Comment by Abhishek1103** [comment]
@mansya yeah..its consistent with the color scheme...its very good... ;-D

**Comment by mansya** [comment]
I have upload all file to this link. you can check in this link
https://drive.google.com/open?id=1ZBWAx03aYp_1ZEbttM6Lgl-t7CZNrhZF
